$ErrorActionPreference = 'Stop'
$skillRoot = Split-Path -Parent $PSScriptRoot
$schemaPath = Join-Path $skillRoot 'references\canonical-test-case-schema.yaml'
if (-not (Test-Path -LiteralPath $schemaPath)) { throw 'Canonical schema missing.' }
$required = @('id','api_id','feature_id','endpoint','source','requirement_ids','technique','title','objective','preconditions','request','test_data','expected_status','expected_schema','expected_business_result','expected_state','audit_status','audit_reason','correction','why_ai_missed','execution_status','failure_classification','bug_id','notes')
$requirementExtraction = [ordered]@{ classification = 'AUTHORITATIVE_REQUIREMENT'; endpoint = 'POST /synthetic/items'; purpose = 'Synthetic smoke-only operation'; authentication = 'Bearer variable' }
$case = [ordered]@{ id='SMOKE-WF-001'; api_id='SMOKE'; feature_id='SMOKE-FR'; endpoint='POST /synthetic/items'; source='AI_GENERATED'; requirement_ids=@('SMOKE-REQ-01'); technique=@('DOMAIN_PARTITION','SCHEMA'); title='Accept valid synthetic value'; objective='Validate a schema-backed success candidate'; preconditions=@(); request=@{method='POST';headers=@{Authorization='Bearer {{token}}'};body=@{value='ok'}}; test_data=@{value='ok'}; expected_status=200; expected_schema=@{type='object'}; expected_business_result='Synthetic acceptance only'; expected_state=$null; audit_status='VALID'; audit_reason='Synthetic contract is internally traceable.'; correction=$null; why_ai_missed=$null; execution_status='NOT_IMPLEMENTED'; failure_classification=$null; bug_id=$null; notes='TEST-ONLY fixture' }
$candidate = [ordered]@{}; foreach ($entry in $case.GetEnumerator()) { $candidate[$entry.Key] = $entry.Value }; $candidate.id='SMOKE-WF-EXT-001'; $candidate.lifecycle_state='STUDENT_EXTENSION_CANDIDATE'; $candidate.audit_status='INCOMPLETE'; $candidate.audit_reason='Needs student review.'; $candidate.why_ai_missed='SECURITY_REASONING_GAP'; $candidate.execution_status='REAL_EXECUTION_REQUIRED'
foreach ($record in @($case,$candidate)) { foreach ($field in $required) { if (-not $record.Contains($field)) { throw "Missing canonical field: $field" } } }
if ($candidate.source -eq 'STUDENT_ADDED' -or $candidate.lifecycle_state -ne 'STUDENT_EXTENSION_CANDIDATE') { throw 'Extension candidate labeling is unsafe.' }
$auditGuard = @('AUDIT_ENTRY_REQUIRED','AUDIT_ENTRY_WRITTEN','AUDIT_ENTRY_VERIFIED')
if ($requirementExtraction.classification -ne 'AUTHORITATIVE_REQUIREMENT' -or $case.audit_status -notin @('VALID','INVALID','INCOMPLETE') -or 'TEST_DESIGN_REVIEW_REQUIRED' -ne 'TEST_DESIGN_REVIEW_REQUIRED' -or $auditGuard.Count -ne 3 -or $auditGuard[-1] -ne 'AUDIT_ENTRY_VERIFIED') { throw 'Workflow checkpoint or audit-guard contract invalid.' }
Write-Output 'PASS: synthetic TEST-ONLY requirement extraction, canonical record, audit status, extension candidate, audit guard, and TEST_DESIGN_REVIEW_REQUIRED checkpoint verified. No SUT/API execution occurred.'
